[book]
authors = ["Nguyen Tran Hau"]
language = "en"
multilingual = false
src = "src"
title = "Today I learned"

[build]
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
